### ISSUE TITLE
List inputs in processes incorrectly set if not specified

### ISSUE THREAD

**Issue by mzganec** [genialis/resolwe#332]
A process
```
- slug: test-list2
  name: Test list2
  requirements:
    expression-engine: jinja
  data_name: 'Test list2'
  version: 0.0.2
  type: data:clustering:hierarchical:sample
  category: analyses
  persistence: TEMP
  description: >
    Test list.
  input:
    - name: genes
      label: Gene subset
      type: list:basic:string
      required: false
  run:
    runtime: polyglot
    language: bash
    program: |
      re-error "Genes: 1{{genes}}2"
      re-progress 1.0
```

called from resdk by specifying an empty set `[]` for `genes` input
`res.run('test-list2', input={'genes': []}, collections=[6])`
correctly returns
`Genes: 1[]2`.

If, however, you call the process by omitting the `genes` input
`res.run('test-list2', input={}, collections=[6])`
you get
`Genes: 1"2`.
Inserting `"` instead of an empty list `[]` when an input is not specified is incorrect.

Consequently a Jinja2 check
`{% if not genes %}`
in the `run` section of the process behaves incorrectly as well.
